# permissions for end users to view valistacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: valistack-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: loki-operator
    app.kubernetes.io/part-of: loki-operator
    app.kubernetes.io/managed-by: kustomize
  name: valistack-viewer-role
rules:
- apiGroups:
  - monitoring.gardener.cloud.gardener.cloud
  resources:
  - valistacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.gardener.cloud.gardener.cloud
  resources:
  - valistacks/status
  verbs:
  - get
